# Development profile configuration
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  config:
    activate:
      on-profile: development

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.example.backend.oems: DEBUG
    org.springframework.security: DEBUG

app:
  environment: development

---
# Production profile configuration
spring:
  config:
    activate:
      on-profile: production

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.example.backend.oems: INFO
    org.springframework.security: WARN

app:
  environment: production

---
# Staging profile configuration
spring:
  config:
    activate:
      on-profile: staging

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.example.backend.oems: INFO
    org.springframework.security: INFO

app:
  environment: staging
